apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: plex
  labels:
    app: radarr
spec:
  type: ClusterIP
  ports:
  - port: 7878
    targetPort: 7878
    protocol: TCP
    name: http
  selector:
    app: radarr
