apiVersion: v1
kind: ConfigMap
metadata:
  name: homeassistant-configuration
  namespace: homeassistant
data:
  configuration.yaml: |
    # Minimal config to allow reverse proxies in the cluster
    http:
      use_x_forwarded_for: true
      trusted_proxies:
        - 127.0.0.1
        - 100.96.0.0/12
    # Add other minimal config options below if needed
