apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homeassistant
resources:
  - namespace.yaml
  - config-pvc.yaml
  - deployment.yaml
  - service.yaml
  # configmap-configuration.yaml removed: configuration is provided via PVC `homeassistant-config`
