apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-token
    namespace: flux-system
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:FgRwZPzjins2xIjHIgMqbbWGK2iLgLw=,iv:eGTzCDjin9zVpYoKz8Qj8tS+Rc7XANvSsOGTgDa15k8=,tag:qI15qFrox/9lXIT0DoUBbQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g4r5ssj30a6yjrnhx3hyty8cgnrrupmkafu6xd0nl0uy9l5hx5rspymlca
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsYVBPdmxqRy9pcGJTOFpp
            WXR6TURaWElHbStDOWlGVGJUOVJhOTB4NHlFCnluWDkyZ3VFcFJJbGU0ZzdOS1Z3
            cGRaUEpzcHhkNTM5K2M1ZmRPLyt1aWMKLS0tIEllTnN6TU9LS28zcHQ0M0FLZDlh
            dm5OOGVGYjNGQ1hMTzF4SUpyNnJvMkEK+0YBPd3bSdnztXsFCL0mbHa2lvbclAaj
            tv0GLfIp1EpIJDmuL3MV5Qk/xAQU6BL89jWEDQPrfedW9z/tVFQnrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-13T13:00:40Z"
    mac: ENC[AES256_GCM,data:0ohHDQUU/mscNPDnycek7MAWCk8C/TdKkKz55ivgS8oOi9WdCGGl1G/FNmaz+3UXLJ/6P1Pcb07uLa15iOv2jou4IXH68PNi//coMVeqZtZRp6xgHrNHQ/MyKYN4gz0BdUxRtq+JSrIzyVWkznuB1nm4p2C3pMcFT7W5RA2IfuU=,iv:pBjurwF18Wzr9gm56J/S6/QK/i1ZrIF7/DgOTuzkw8I=,tag:5Wv27c88pqhCSQ6BU3emPQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
