apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: personal-cluster
spec:
  hosts:
    - ssh:
        address: oci
        user: ubuntu
        port: 22
        keyPath: ~/.ssh/id_rsa
      privateInterface: tailscale0
      role: controller+worker
      hostname: oci
      noTaints: true
    - ssh:
        address: media
        user: home
        port: 22
        keyPath: ~/.ssh/id_rsa
      privateInterface: tailscale0
      role: worker
      hostname: media
    - ssh:
        address: nanocluster1
        user: sipeed
        port: 22
        keyPath: ~/.ssh/id_rsa
      privateInterface: tailscale0
      role: worker
      hostname: nanocluster-1
    - ssh:
        address: nanocluster2
        user: sipeed
        port: 22
        keyPath: ~/.ssh/id_rsa
      privateInterface: tailscale0
      role: worker
      hostname: nanocluster-2
    - ssh:
        address: nanocluster3
        user: sipeed
        port: 22
        keyPath: ~/.ssh/id_rsa
      privateInterface: tailscale0
      role: worker
      hostname: nanocluster-3
    - ssh:
        address: nanocluster4
        user: sipeed
        port: 22
        keyPath: ~/.ssh/id_rsa
      privateInterface: tailscale0
      role: worker
      hostname: nanocluster-4
    - ssh:
        address: nanocluster5
        user: sipeed
        port: 22
        keyPath: ~/.ssh/id_rsa
      privateInterface: tailscale0
      role: worker
      hostname: nanocluster-5
    - ssh:
        address: nanocluster6
        user: sipeed
        port: 22
        keyPath: ~/.ssh/id_rsa
      privateInterface: tailscale0
      role: worker
      hostname: nanocluster-6
  k0s:
    config:
      spec:
        api:
          address: 100.70.234.18
        network:
          provider: calico
          calico:
            envVars:
              FELIX_IPTABLESMARKMASK: "0xff00ff00"
              IP_AUTODETECTION_METHOD: "interface=tailscale0"
        extensions:
          helm:
            repositories:
              - name: openebs-internal
                url: https://openebs.github.io/charts
            charts:
              - name: openebs
                chartname: openebs-internal/openebs
                version: "3.9.0"
                namespace: openebs
                order: 1
                values: |
                  localprovisioner:
                    hostpathClass:
                      enabled: true
                      isDefaultClass: true
