apiVersion: v1
kind: PersistentVolume
metadata:
  name: timescaledb-data-pv
spec:
  capacity:
    storage: 1Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: openebs-hostpath
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - media
  hostPath:
    path: /var/lib/cluster-storage/timescaledb/data
    type: DirectoryOrCreate
