apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: plex
resources:
  - namespace.yaml
  - media-shared-pv.yaml
  - media-shared-pvc.yaml
  # TODO: Add other Plex resources here
  # - deployment.yaml
  # - service.yaml
  # - ingress.yaml (if needed)