apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: plex
resources:
  - namespace.yaml
  - media-shared-pv.yaml
  - media-shared-pvc.yaml
  - config-pvc.yaml
  - deployment.yaml
  - service.yaml
