apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-shared-pv
spec:
  capacity:
    storage: 916Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: media-local
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - media
  hostPath:
    path: /mnt/hdd
    type: Directory
