apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana-k8s-monitoring
  namespace: monitoring
spec:
  interval: 5m
  releaseName: grafana-k8s-monitoring
  chart:
    spec:
      chart: k8s-monitoring
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  install:
    createNamespace: false
  valuesFrom:
    # Reference a Secret that contains the full values YAML under the key `values.yaml`.
    - kind: Secret
      name: grafana-k8s-monitoring-values
