apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: radarr-latest
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: radarr
  filterTags:
    pattern: '^latest$'
  policy:
    alphabetical:
      order: asc
