apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: qbittorrent-latest
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: qbittorrent
  interval: 168h
  filterTags:
    pattern: "^latest$"
  policy:
    alphabetical:
      order: asc
  digestReflectionPolicy: Always
