apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: qbittorrent-latest
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: qbittorrent
  filterTags:
    pattern: "^latest$"
  policy:
    alphabetical: {}
