apiVersion: apps/v1
kind: Deployment
metadata:
  name: windmill-worker
  namespace: windmill
  labels:
    app: windmill-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: windmill-worker
  template:
    metadata:
      labels:
        app: windmill-worker
    spec:
      containers:
        - name: windmill-worker
          image: windmill/windmill:main
          env:
            - name: MODE
              value: worker
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: timescale-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: timescale-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: timescale-secret
                  key: POSTGRES_DB
            - name: POSTGRES_HOST
              value: timescaledb.timescale.svc.cluster.local
            - name: POSTGRES_PORT
              value: "5432"
            - name: DATABASE_URL
              value: postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB)
          volumeMounts:
            - mountPath: /tmp/windmill/logs
              name: worker-logs
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
      volumes:
        - name: worker-logs
          persistentVolumeClaim:
            claimName: windmill-worker-logs
