apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: windmill-worker-logs
  namespace: windmill
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: windmill-worker-cache
  namespace: windmill
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
