apiVersion: v1
kind: Service
metadata:
  name: windmill-server
  namespace: windmill
spec:
  selector:
    app: windmill-server
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      name: http
    - protocol: TCP
      port: 2525
      targetPort: 2525
      name: metrics
  type: ClusterIP
