apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: flux-system-alerts
  namespace: flux-system
spec:
  providerRef:
    name: discord
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: '*'
    - kind: Kustomization
      name: '*'
    - kind: HelmRepository
      name: '*'
    - kind: HelmRelease
      name: '*'
  summary: "Flux notification for cluster {{ .InvolvedObject.Name }}"
  inclusionList:
    - ".*reconciliation succeeded.*"
    - ".*reconciliation failed.*"
    - ".*health check failed.*"
    - ".*dependency.*"
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: application-alerts
  namespace: flux-system
spec:
  providerRef:
    name: discord
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: '*'
      namespace: flux-system
    - kind: HelmRelease
      name: '*'
      namespace: '*'
  summary: "Application {{ .InvolvedObject.Name }} notification"
  inclusionList:
    - ".*ready.*"
    - ".*failed.*"
    - ".*suspended.*"