apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: kubernetes-system-alerts
  namespace: flux-system
spec:
  providerRef:
    name: discord
  eventSeverity: error  # Only show errors for k8s resources to avoid spam
  eventSources:
    # Core Kubernetes Resources
    - kind: Pod
      name: '*'
    - kind: Deployment  
      name: '*'
    - kind: ReplicaSet
      name: '*'
    - kind: Service
      name: '*'
    - kind: Node
      name: '*'
    - kind: PersistentVolumeClaim
      name: '*'
    - kind: ConfigMap
      name: '*'
    - kind: Secret
      name: '*'