apiVersion: v1
kind: Service
metadata:
  name: timescaledb
  namespace: timescale
spec:
  selector:
    app: timescaledb
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
