name: Create PR for Flux Image Updates

on:
  push:
    branches:
      - flux-image-updates

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if PR already exists
        id: check-pr
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=$(gh pr list --head flux-image-updates --base main --json number --jq '.[0].number // 0')
          echo "number=$PR_NUMBER" >> $GITHUB_OUTPUT

      - name: Create or Update Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ steps.check-pr.outputs.number }}
        run: |
          PR_BODY="## Automated Image Updates by FluxCD

          This PR contains automated updates to container image tags detected by Flux image automation.

          ### What changed?

          Flux has detected newer image versions and updated the deployment manifests accordingly.

          ### Review Checklist
          - [ ] Review the image tag changes
          - [ ] Verify the new versions are expected
          - [ ] Check for any breaking changes in release notes

          ---

          🤖 This PR was automatically created by the Flux image automation workflow.
          Last updated: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"

          if [ "$PR_NUMBER" = "0" ]; then
            echo "Creating new PR..."
            gh pr create \
              --base main \
              --head flux-image-updates \
              --title "chore: Update container images" \
              --body "$PR_BODY" || echo "PR creation failed or already exists"
          else
            echo "PR #$PR_NUMBER already exists, updating..."
            gh pr edit "$PR_NUMBER" \
              --body "$PR_BODY" || echo "PR update failed"
          fi
